// <auto-generated />
using System;
using FA.LibraryManagement.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FA.LibraryManagement.Core.Migrations
{
    [DbContext(typeof(LibraryManagementContext))]
    [Migration("20240516071059_RemoveDateTimeForPublisherDate")]
    partial class RemoveDateTimeForPublisherDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Stephen Breyer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dr. Seuss"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Robert Greene"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Crystal Radke"
                        },
                        new
                        {
                            Id = 5,
                            Name = "The Beginner's Bible"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Adam Higginbotham"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Publications International Ltd"
                        });
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("PublishedDate")
                        .HasColumnType("date");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A provocative, brilliant analysis by recently retired Supreme Court Justice Stephen Breyer that deconstructs the textualist philosophy of the current Supreme Court’s supermajority and makes the case for a better way to interpret the Constitution.\n\n“You will not read a more important legal work this election year.” —Bob Woodward,Washington Post reporter and author of fifteen #1 New York Times bestselling books\n“A dissent for the ages.” —The Washington Post\n“Breyer’s candor about the state of the court is refreshing and much needed.” —The Boston Globe\n\nThe relatively new judicial philosophy of textualism dominates the Supreme Court. Textualists claim that the right way to interpret the Constitution and statutes is to read the text carefully and examine the language as it was understood at the time the documents were written.\n\nThis, however, is not Justice Breyer’s philosophy nor has it been the traditional way to interpret the Constitution since the time of Chief Justice John Marshall. Justice Breyer recalls Marshall’s exhortation that the Constitution must be a workable set of principles to be interpreted by subsequent generations.\n\nMost important in interpreting law, says Breyer, is to understand the purposes of statutes as well as the consequences of deciding a case one way or another. He illustrates these principles by examining some of the most important cases in the nation’s history, among them the Dobbs and Bruen decisions from 2022 that he argues were wrongly decided and have led to harmful results.\n",
                            ISBN = "978-1668021538",
                            PublishedDate = new DateOnly(2024, 3, 26),
                            Publisher = "Simon & Schuster",
                            Quantity = 10,
                            Title = "Reading the Constitution: Why I Chose Pragmatism, Not Textualism"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "A sitting justice reflects upon the authority of the Supreme Court―how that authority was gained and how measures to restructure the Court could undermine both the Court and the constitutional system of checks and balances that depends on it.\n\nA growing chorus of officials and commentators argues that the Supreme Court has become too political. On this view the confirmation process is just an exercise in partisan agenda-setting, and the jurists are no more than “politicians in robes”―their ostensibly neutral judicial philosophies mere camouflage for conservative or liberal convictions.",
                            ISBN = "978-0674269361",
                            PublishedDate = new DateOnly(2021, 9, 14),
                            Publisher = "Harvard University Press",
                            Quantity = 20,
                            Title = "The Authority of the Court and the Peril of Politics"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Say “happy birthday,” Dr. Seuss-style! This classic picture book whisks readers away on the most spectacular birthday of all time—and reminds them to celebrate themselves every day of the year!\n\nI wish we could do what they do in Katroo.\nThey sure know how to say “Happy birthday to you!”\n\nWhen the Great Birthday Bird of Katroo arrives to usher in your “Day of all Days,” you can expect a colorful romp full of fantastical fun that is all about YOU! Treat yourself to flowers that smell like licorice and cheese. Pick out the world’s tallest pet—or a nice Time-Telling Fish. Then prepare for a party so grand it will take twenty days just to sweep up the mess.\n\nFeaturing birthday festivities on every page, this joyful classic from the one and only Dr. Seuss rejoices in the person you were born to be!",
                            ISBN = "978-0394800769",
                            PublishedDate = new DateOnly(1959, 8, 12),
                            Publisher = "Random House Books for Young Readers",
                            Quantity = 20,
                            Title = "Happy Birthday to You!"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Say “happy birthday,” Dr. Seuss-style! This classic picture book whisks readers away on the most spectacular birthday of all time—and reminds them to celebrate themselves every day of the year!\n\nI wish we could do what they do in Katroo.\nThey sure know how to say “Happy birthday to you!”\n\nWhen the Great Birthday Bird of Katroo arrives to usher in your “Day of all Days,” you can expect a colorful romp full of fantastical fun that is all about YOU! Treat yourself to flowers that smell like licorice and cheese. Pick out the world’s tallest pet—or a nice Time-Telling Fish. Then prepare for a party so grand it will take twenty days just to sweep up the mess.\n\nFeaturing birthday festivities on every page, this joyful classic from the one and only Dr. Seuss rejoices in the person you were born to be!",
                            ISBN = "978-0375872334",
                            PublishedDate = new DateOnly(2013, 11, 5),
                            Publisher = "Random House Books for Young Readers",
                            Quantity = 20,
                            Title = "Oh Say Can You Say? (Dr. Seuss Collector's Edition)"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Amoral, cunning, ruthless, and instructive, this multi-million-copy New York Times bestseller is the definitive manual for anyone interested in gaining, observing, or defending against ultimate control – from the author of The Laws of Human Nature.\n\nIn the book that People magazine proclaimed “beguiling” and “fascinating,” Robert Greene and Joost Elffers have distilled three thousand years of the history of power into 48 essential laws by drawing from the philosophies of Machiavelli, Sun Tzu, and Carl Von Clausewitz and also from the lives of figures ranging from Henry Kissinger to P.T. Barnum.\n \nSome laws teach the need for prudence (“Law 1: Never Outshine the Master”), others teach the value of confidence (“Law 28: Enter Action with Boldness”), and many recommend absolute self-preservation (“Law 15: Crush Your Enemy Totally”). Every law, though, has one thing in common: an interest in total domination. In a bold and arresting two-color package, The 48 Laws of Power is ideal whether your aim is conquest, self-defense, or simply to understand the rules of the game.",
                            ISBN = "978-0140280197",
                            PublishedDate = new DateOnly(2000, 9, 1),
                            Publisher = "Penguin Books",
                            Quantity = 20,
                            Title = "The 48 Laws of Power"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Please Note That The Following Individual Books As Per Original ISBN and Cover Image In this Listing shall be Dispatched The Daily Laws and The 33 Strategies of War by Robert Greene 2 Books Collection Set : The Daily Over the last 25 years, Robert Greene has provided insights into every aspect of being whether that be getting what you want, understanding others' motivations, mastering your impulses, or recognising strengths and weaknesses. The Daily Laws distills that wisdom into easy-to-digest daily entries whose content spans power, seduction, war, strategy, politics, productivity, psychology, leadership, and adversity.Not only is this beautifully designed volume the perfect entry point for those new to Greene's penetrating insight. The 33 Strategies of From bestselling author Robert Greene comes a brilliant distillation of the strategies of war that can help us gain mastery in the modern world. Spanning world civilisations, and synthesising dozens of political, philosophical, and religious texts, The 33 Strategies of War is a comprehensive guide to the subtle social game of everyday life. Based on profound, timeless lessons, it is abundantly illustrated with examples of the genius and folly of everyone from Napoleon to Margaret Thatcher and Hannibal to Ulysses S. Grant, as well as diplomats, captains of industry and Samurai swordsmen.",
                            ISBN = "978-9124292041",
                            PublishedDate = new DateOnly(2023, 12, 7),
                            Publisher = "Profile Books",
                            Quantity = 20,
                            Title = "The Daily Laws and The 33 Strategies of War by Robert Greene 2 Books Collection Set"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Help your little one build communication skills with the ultimate writing workbook for kids ages 3 to 5. More than 1 million copies sold!\n\nSet kids up to succeed in school with a learn to write for kids guide that offers letter, shape, and number practice for kindergarten—and beyond. My First Learn-to-Write Workbook introduces early writers to proper pen control, line tracing, and more with dozens of handwriting exercises that engage their minds and boost their reading and writing comprehension.",
                            ISBN = "978-1641526272",
                            PublishedDate = new DateOnly(2019, 8, 27),
                            Publisher = "Rockridge Press",
                            Quantity = 20,
                            Title = "My First Learn-to-Write Workbook: Practice for Kids with Pen Control, Line Tracing, Letters, and More!"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Millions of children and their parents can’t be wrong. The bright and vibrant illustrations enhance every word of The Beginner’s Bible® to produce one of the most moving and memorable Bible experiences a young child can have.\n\nThe Beginner’s Bible is where a child’s journey towards a lifelong love of God’s Word begins.\n\nKids will enjoy reading the story of Noah’s Ark as they see Noah helping the elephant onto the big boat. They will learn about the prophet Jonah as they see him praying inside the fish. And they will follow along with the text of Jesus’ ministry as they see a man in need of healing lowered down through the roof of a house.\n\nParents, teachers, pastors, and children will rediscover these beloved parables and so much more as they read more than 90 stories in The Beginner's Bible, just like millions of children before. The Beginner’s Bible® brand has been trusted for nearly 30 years, with more than 25 million products sold.",
                            ISBN = "978-0310750130",
                            PublishedDate = new DateOnly(2016, 10, 4),
                            Publisher = "Zonderkidz",
                            Quantity = 20,
                            Title = "The Beginner's Bible: Timeless Children's Stories"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "The legendary New York Times bestselling tale of top-down change for anyone trying to navigate today's uncertain business seas.\n\nWhen Captain Abrashoff took over as commander of USS Benfold, it was like a business that had all the latest technology but only some of the productivity. Knowing that responsibility for improving performance rested with him, he realized he had to improve his own leadership skills before he could improve his ship. Within months, he created a crew of confident and inspired problem-solvers eager to take the initiative and responsibility for their actions. The slogan on board became \"It's your ship,\" and Benfold was soon recognized far and wide as a model of naval efficiency. How did Abrashoff do it? Against the backdrop of today's United States Navy, Abrashoff shares his secrets of successful management including:\n",
                            ISBN = "978-1455523023",
                            PublishedDate = new DateOnly(2012, 10, 9),
                            Publisher = "Grand Central Publishing",
                            Quantity = 20,
                            Title = "It's Your Ship: Management Techniques from the Best Damn Ship in the Navy, 10th Anniversary Edition"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "100 Cars That Changed the World showcases vehicles from the end of the nineteenth century to 2020.\nCars are showcased with brief text, color photography, and vintage black and white photography.\nVehicles included:\nThe Ford Model T that put America on wheels.\nThe Volkswagen Beetle that was loved around the world.\nThe Jeep that helped win World War II and popularized off-road adventure.\nThe Pontiac GTO that launched the muscle car era.\nThe Dodge Caravan that changed the way that families travel.\nThe Ford Explorer that ignited the SUV movement.\nThe Tesla Model S that made electric cars exciting.\nAnd many more!\nLarge hardcover book, 144 pages.",
                            ISBN = "978-1645581246",
                            PublishedDate = new DateOnly(2020, 3, 25),
                            Publisher = "Walter Foster Publishing",
                            Quantity = 20,
                            Title = "100 Cars That Changed the World: The Designs, Engines, and Technologies That Drive Our Imaginations"
                        });
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 5
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 6
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 7
                        });
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.BookImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            ImageUrl = "https://m.media-amazon.com/images/I/6118UMWll-L._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            ImageUrl = "https://m.media-amazon.com/images/I/71agAaqCyOL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 2,
                            ImageUrl = "https://m.media-amazon.com/images/I/51B5-WqrHVS._SL1000_.jpg"
                        },
                        new
                        {
                            Id = 4,
                            BookId = 3,
                            ImageUrl = "https://m.media-amazon.com/images/I/61-66t0NIpL._SL1200_.jpg"
                        },
                        new
                        {
                            Id = 5,
                            BookId = 4,
                            ImageUrl = "https://m.media-amazon.com/images/I/91i1FNtjk4L._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 6,
                            BookId = 5,
                            ImageUrl = "https://m.media-amazon.com/images/I/611X8GI7hpL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 7,
                            BookId = 6,
                            ImageUrl = "https://m.media-amazon.com/images/I/81CE5Iz9VwL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 8,
                            BookId = 6,
                            ImageUrl = "https://m.media-amazon.com/images/I/91-99A2X5dL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 9,
                            BookId = 6,
                            ImageUrl = "https://m.media-amazon.com/images/I/71SOwtHPbBL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 10,
                            BookId = 7,
                            ImageUrl = "https://m.media-amazon.com/images/I/71ZIPHcr-PL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 11,
                            BookId = 7,
                            ImageUrl = "https://m.media-amazon.com/images/I/71P9+nFqnhL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 12,
                            BookId = 7,
                            ImageUrl = "https://m.media-amazon.com/images/I/71dxLbzeEoL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 13,
                            BookId = 7,
                            ImageUrl = "https://m.media-amazon.com/images/I/71EYOUrNnXL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 14,
                            BookId = 7,
                            ImageUrl = "https://m.media-amazon.com/images/I/71ZIPHcr-PL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 15,
                            BookId = 7,
                            ImageUrl = "https://m.media-amazon.com/images/I/71qx0ZSysML._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 16,
                            BookId = 7,
                            ImageUrl = "https://m.media-amazon.com/images/I/71d6Ex5i4zL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 17,
                            BookId = 7,
                            ImageUrl = "https://m.media-amazon.com/images/I/71D8-vq6AYL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 18,
                            BookId = 8,
                            ImageUrl = "https://m.media-amazon.com/images/I/81Pic6bOvuL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 19,
                            BookId = 8,
                            ImageUrl = "https://m.media-amazon.com/images/I/91OZJW0dZnL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 20,
                            BookId = 9,
                            ImageUrl = "https://m.media-amazon.com/images/I/71wWNi5YymL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 21,
                            BookId = 9,
                            ImageUrl = "https://m.media-amazon.com/images/I/81zNT-wG8hL._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 22,
                            BookId = 10,
                            ImageUrl = "https://m.media-amazon.com/images/I/71dNRskgj7L._SL1500_.jpg"
                        },
                        new
                        {
                            Id = 23,
                            BookId = 10,
                            ImageUrl = "https://m.media-amazon.com/images/I/81LDFz47KSL._SL1500_.jpg"
                        });
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.Borrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BorrowedTime")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Borrowings");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.BorrowingDetail", b =>
                {
                    b.Property<int>("BorrowId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DueTime")
                        .HasColumnType("date");

                    b.Property<float>("Fine")
                        .HasColumnType("real");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReturnTime")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("BorrowId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BorrowingDetails");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Law"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Teen & Young Adult"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Politics & Social Sciences"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Education & Teaching"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Engineering & Transportation"
                        });
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BorrowedTime")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DueTime")
                        .HasColumnType("date");

                    b.Property<float>("Fine")
                        .HasColumnType("real");

                    b.Property<DateOnly?>("ReturnedTime")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is role : librarian",
                            Name = "Librarian",
                            NormalizedName = "LIBRARIAN",
                            RoleId = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is role : member",
                            Name = "Member",
                            NormalizedName = "MEMBER",
                            RoleId = 0
                        });
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1999, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "225095a0-5ce9-4ebc-a51c-08d11a168f78",
                            Email = "trungsangle123@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Trung",
                            Gender = "Male",
                            LastName = "Sang",
                            LockoutEnabled = false,
                            NormalizedEmail = "TRUNGSANGLE123@GMAIL.COM",
                            NormalizedUserName = "SANGLT12",
                            PasswordHash = "AQAAAAIAAYagAAAAEF+kflztPRzXy/uVDeXi7oc4yNo5ze+AtYcauF4WpN9sZX4/bUJZXgWBftHDzeAVRw==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "23XYSO4Z3J4WWLXHGVQ35GIRRDPNVN2R",
                            TwoFactorEnabled = false,
                            UserName = "SangLT12"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2001, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "225095a0-5ce9-4ebc-a51c-08d11a168f78",
                            Email = "hao.nn151201@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Ngoc",
                            Gender = "Male",
                            LastName = "Hao",
                            LockoutEnabled = false,
                            NormalizedEmail = "HAONN1@GMAIL.COM",
                            NormalizedUserName = "HAONN1",
                            PasswordHash = "AQAAAAIAAYagAAAAEF+kflztPRzXy/uVDeXi7oc4yNo5ze+AtYcauF4WpN9sZX4/bUJZXgWBftHDzeAVRw==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "23XYSO4Z3J4WWLXHGVQ35GIRRDPNVN2R",
                            TwoFactorEnabled = false,
                            UserName = "HaoNN1"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2001, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "225095a0-5ce9-4ebc-a51c-08d11a168f78",
                            Email = "vomanhdung276@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Vo",
                            Gender = "Male",
                            LastName = "Dung",
                            LockoutEnabled = false,
                            NormalizedEmail = "DUNGVM7@GMAIL.COM",
                            NormalizedUserName = "DUNGVM7",
                            PasswordHash = "AQAAAAIAAYagAAAAEF+kflztPRzXy/uVDeXi7oc4yNo5ze+AtYcauF4WpN9sZX4/bUJZXgWBftHDzeAVRw==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "23XYSO4Z3J4WWLXHGVQ35GIRRDPNVN2R",
                            TwoFactorEnabled = false,
                            UserName = "DungVM7"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2001, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "225095a0-5ce9-4ebc-a51c-08d11a168f78",
                            Email = "member001@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Member",
                            Gender = "Male",
                            LastName = "Test 001",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER001@GMAIL.COM",
                            NormalizedUserName = "MEMBER001",
                            PasswordHash = "AQAAAAIAAYagAAAAEF+kflztPRzXy/uVDeXi7oc4yNo5ze+AtYcauF4WpN9sZX4/bUJZXgWBftHDzeAVRw==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "23XYSO4Z3J4WWLXHGVQ35GIRRDPNVN2R",
                            TwoFactorEnabled = false,
                            UserName = "Member001"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2001, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "225095a0-5ce9-4ebc-a51c-08d11a168f78",
                            Email = "member002@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Member",
                            Gender = "Male",
                            LastName = "Test 002",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER002@GMAIL.COM",
                            NormalizedUserName = "MEMBER002",
                            PasswordHash = "AQAAAAIAAYagAAAAEF+kflztPRzXy/uVDeXi7oc4yNo5ze+AtYcauF4WpN9sZX4/bUJZXgWBftHDzeAVRw==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "23XYSO4Z3J4WWLXHGVQ35GIRRDPNVN2R",
                            TwoFactorEnabled = false,
                            UserName = "Member002"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2001, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "225095a0-5ce9-4ebc-a51c-08d11a168f78",
                            Email = "member003@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Member",
                            Gender = "Male",
                            LastName = "Test 003",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER003@GMAIL.COM",
                            NormalizedUserName = "MEMBER003",
                            PasswordHash = "AQAAAAIAAYagAAAAEF+kflztPRzXy/uVDeXi7oc4yNo5ze+AtYcauF4WpN9sZX4/bUJZXgWBftHDzeAVRw==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "23XYSO4Z3J4WWLXHGVQ35GIRRDPNVN2R",
                            TwoFactorEnabled = false,
                            UserName = "Member003"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2001, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "225095a0-5ce9-4ebc-a51c-08d11a168f78",
                            Email = "member004@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Member",
                            Gender = "Male",
                            LastName = "Test 004",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER004@GMAIL.COM",
                            NormalizedUserName = "MEMBER004",
                            PasswordHash = "AQAAAAIAAYagAAAAEF+kflztPRzXy/uVDeXi7oc4yNo5ze+AtYcauF4WpN9sZX4/bUJZXgWBftHDzeAVRw==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "23XYSO4Z3J4WWLXHGVQ35GIRRDPNVN2R",
                            TwoFactorEnabled = false,
                            UserName = "Member004"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2001, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "225095a0-5ce9-4ebc-a51c-08d11a168f78",
                            Email = "member005@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Member",
                            Gender = "Male",
                            LastName = "Test 005",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER005@GMAIL.COM",
                            NormalizedUserName = "MEMBER005",
                            PasswordHash = "AQAAAAIAAYagAAAAEF+kflztPRzXy/uVDeXi7oc4yNo5ze+AtYcauF4WpN9sZX4/bUJZXgWBftHDzeAVRw==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "23XYSO4Z3J4WWLXHGVQ35GIRRDPNVN2R",
                            TwoFactorEnabled = false,
                            UserName = "Member005"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2001, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "225095a0-5ce9-4ebc-a51c-08d11a168f78",
                            Email = "member006@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Member",
                            Gender = "Male",
                            LastName = "Test 006",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER006@GMAIL.COM",
                            NormalizedUserName = "MEMBER006",
                            PasswordHash = "AQAAAAIAAYagAAAAEF+kflztPRzXy/uVDeXi7oc4yNo5ze+AtYcauF4WpN9sZX4/bUJZXgWBftHDzeAVRw==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "23XYSO4Z3J4WWLXHGVQ35GIRRDPNVN2R",
                            TwoFactorEnabled = false,
                            UserName = "Member006"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2001, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "225095a0-5ce9-4ebc-a51c-08d11a168f78",
                            Email = "member007@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Member",
                            Gender = "Male",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER007@GMAIL.COM",
                            NormalizedUserName = "MEMBER007",
                            PasswordHash = "AQAAAAIAAYagAAAAEF+kflztPRzXy/uVDeXi7oc4yNo5ze+AtYcauF4WpN9sZX4/bUJZXgWBftHDzeAVRw==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "23XYSO4Z3J4WWLXHGVQ35GIRRDPNVN2R",
                            TwoFactorEnabled = false,
                            UserName = "Member007"
                        });
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.UserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.Book", b =>
                {
                    b.HasOne("FA.LibraryManagement.Core.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.BookAuthor", b =>
                {
                    b.HasOne("FA.LibraryManagement.Core.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FA.LibraryManagement.Core.Models.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.BookImage", b =>
                {
                    b.HasOne("FA.LibraryManagement.Core.Models.Book", "Book")
                        .WithMany("BookImages")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.Borrowing", b =>
                {
                    b.HasOne("FA.LibraryManagement.Core.Models.User", "User")
                        .WithMany("Borrowings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.BorrowingDetail", b =>
                {
                    b.HasOne("FA.LibraryManagement.Core.Models.Book", "Book")
                        .WithMany("BorrowingDetails")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FA.LibraryManagement.Core.Models.Borrowing", "Borrowing")
                        .WithMany("BorrowingDetails")
                        .HasForeignKey("BorrowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Borrowing");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.Cart", b =>
                {
                    b.HasOne("FA.LibraryManagement.Core.Models.Book", "Book")
                        .WithMany("Carts")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FA.LibraryManagement.Core.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.History", b =>
                {
                    b.HasOne("FA.LibraryManagement.Core.Models.Book", "Book")
                        .WithMany("Histories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FA.LibraryManagement.Core.Models.User", "User")
                        .WithMany("Histories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.RoleClaim", b =>
                {
                    b.HasOne("FA.LibraryManagement.Core.Models.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.User", b =>
                {
                    b.HasOne("FA.LibraryManagement.Core.Models.Role", null)
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.UserClaim", b =>
                {
                    b.HasOne("FA.LibraryManagement.Core.Models.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.UserLogin", b =>
                {
                    b.HasOne("FA.LibraryManagement.Core.Models.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.UserRole", b =>
                {
                    b.HasOne("FA.LibraryManagement.Core.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FA.LibraryManagement.Core.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.UserToken", b =>
                {
                    b.HasOne("FA.LibraryManagement.Core.Models.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookImages");

                    b.Navigation("BorrowingDetails");

                    b.Navigation("Carts");

                    b.Navigation("Histories");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.Borrowing", b =>
                {
                    b.Navigation("BorrowingDetails");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.Role", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FA.LibraryManagement.Core.Models.User", b =>
                {
                    b.Navigation("Borrowings");

                    b.Navigation("Carts");

                    b.Navigation("Claims");

                    b.Navigation("Histories");

                    b.Navigation("Logins");

                    b.Navigation("Tokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
